### ISSUE TITLE
Analyze and design GitHub log ingestion for Splunk

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/SecDev-Tools#26]

**Comment by edthedev** [comment]
Good technical discussion on the team call today. 

May have a blocker here in that we may need to reach out to @baristaTam  and @MKletz, whose time is prioritized to project Double Barrel right now. If so, feel free to mark this blocked and move on, we can circle back when COVID gives us a break.

**Comment by edthedev** [comment]
Some questions and answers from today's meeting:

Not sure if we can do this at the enterprise level. Can it work at the organizational level? How many organizations do we have?
> We have at least 30 organizations now. Might end up creating an organization per class - could see us having hundreds of organizatinos before too long.
> ED: student classroom logs aren't the audit events we're most concerned with. Security could live with only covering the IT and research orgs, if needed.
> It would be ideal to get it to work at the enterprise level, but let's get something working at the org level and we can revisit.

GitHub has a specific set of logs marked as audit. Is this close enough to what we wanted?
> Yes. Whatever GitHub puts in the audit set by default is fine.
> GitHub decision should be +/- 80% of what we would ask for anyway - and we're looking for a minimum viable product right now.

Do we want to filter any of those logs down before we pull them into Splunk?
> Toss it all into Splunk, we can trim it later.

Do the GitHub audit logs contain anything we don't want - like the contents that we checked in?
> GitHub audit logs are focused on who did what. Includes commit hash, but not the content.

Do GitHub audit logs have enough information for us to start an investigation?
> If they contain author and commit hash, that's likely the sweet spot.
> But we can live with what we get, for now, in any case. We're doing preventative work that can be refined later by specific use cases. We don't want to get bogged down in our wish list today.

**Comment by edthedev** [comment]
DR: Found a lambda blueprint to implement this.
There's also a way to go directly from GitHub to Splunk, but there's security issues - David is reading through the security issues and will reach out to the Splunk team.

**Comment by ddriddle** [comment]
@edthedev I have identified two possible push solutions: 

1. The simplest approach has GitHub directly push json formatted logs via [WebHooks](https://docs.github.com/en/developers/webhooks-and-events/webhooks) to a raw HEC endpoint. GitHub does not have the option of setting the Authorization header, so query string authorization must be used and configured on Splunk by setting [`allowQueryStringAuth`](https://docs.splunk.com/Documentation/Splunk/latest/Data/FormateventsforHTTPEventCollector#Query_string_.28Splunk_Cloud_only.29) to `true`. When using [HTTPS](https://https.cio.gov/faq/#what-information-does-https-protect) the query string is protected from packet sniffing over the network. Even so there is concern that the HEC token could be leaked via logging as query strings are typically logged by servers.
2. An alternative approach described [here](https://www.splunk.com/en_us/blog/tips-and-tricks/getting-github-data-with-webhooks.html) uses a Lambda blueprint to receive data from a GitHub WebHook. GitHub webhooks optionally support a [shared secret](https://docs.github.com/en/developers/webhooks-and-events/securing-your-webhooks) that may be used to create an encrypted hash of each payload. Unfortunately, the published Lambda function does not use this security feature to ensure that only data from the configured webhook is accepted and forwarded to the Splunk HEC endpoint, though the author discusses it. Oddly, the webhook still requires the HEC token be put in a query string which seems to invalidate the reason for this approach, but the author thinks [otherwise](https://www.splunk.com/en_us/blog/tips-and-tricks/getting-github-data-with-webhooks-part-2.html). 

The Lambda function described above is trivial:

```python
import json
import urllib3

def lambda_handler(event, context):
    #Parse URL Parameters
    http_method = event["queryStringParameters"]["http_method"]
    url = event["queryStringParameters"]["url"]
    port = event["queryStringParameters"]["port"]
    token = event["queryStringParameters"]["token"]

    #Build Full URL out of Parameters
    full_url = http_method+'://'+url+':'+port+'/services/collector/raw'
    
    #Create URLLib3 Pool Manager
    http = urllib3.PoolManager()
    urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
    
    #Post Event
    r = http.request('POST', full_url, body=event["body"], headers={'Content-Type': 'application/json', 'Authorization':'Splunk '+token})

    return {
        'statusCode': 200,
        'body':'Success'
    }
```

I do not see any value in using this Lambda function over the first approach described above. If passing the HEC token via a query string to Splunk is a security concern I recommend we write our own Lambda function that uses GitHub's security features described above to ensure only valid input is accepted and forwarded to Splunk. Further I would store the HEC token in Amazon SSM for secure storage and retrieval. I also recommend using a queue to store Webhook events before being sent to Splunk. I recommend this to ensure the Lambda function is robust. Without a queue if an event is sent from Github, but Splunk is down for a short period the event will be lost. With a queue the event can be resent at a latter time. If the security team and the Splunk maintainers are comfortable using query string authorization with HEC then I recommend we use the first approach as it is very simple and involves no code. If not then I recommend we develop our own robust Lambda function.

**References**

1. [Splunking Webhooks with the HTTP Event Collector](https://www.splunk.com/en_us/blog/tips-and-tricks/splunking-webhooks-with-the-http-event-collector.html)
2. [Getting Github Data with Webhooks](https://www.splunk.com/en_us/blog/tips-and-tricks/getting-github-data-with-webhooks.html)
3. [Getting Github Data with Webhooks (Part 2)](https://www.splunk.com/en_us/blog/tips-and-tricks/getting-github-data-with-webhooks-part-2.html)
4. [Introduction to HTTPS: What information does HTTPS protect?](https://https.cio.gov/faq/#what-information-does-https-protect)

**Comment by edthedev** [comment]
On first analysis, my favorite option is to write (and publish as open source) the lambda function that does the correc thing: 
+ Accepts GitHub header auth as GitHub knows how to send it (new code as David describes above)
+ Sends Splunk token auth via POST as in the recipe above.

**Comment by edthedev** [comment]
Let's go ahead and make a first pass at building the correct lambda function, and discuss calling it off (retreat to one of the other options) if it takes more than the rest of this sprint.

**Comment by edthedev** [comment]
This is ready to close after #29

**Comment by edthedev** [comment]
Planning to prototype with LocalStack.

**Comment by ddriddle** [comment]
The disadvantage of the proposed solution, i.e. using a Lambda function, ideally with a queue for maximum reliability, to receive GitHub [audit logs](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/reviewing-the-audit-log-for-your-organization) via [webhooks](https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhooks) is that event logs can be lost if the Lambda function is not available when the webhook is fired. Unfortunately, it does not seem possible to retrieve lost events via GitHubs API. An alternative strategy is to use polling, but this is less desirable, and it was decided not to pursue a polling based solution (See [What is the best way to acquire AuditLog in organization?](https://github.community/t/what-is-the-best-way-to-acquire-auditlog-in-organization/13783/3) for alternative solutions).

**Comment by edthedev** [comment]
<img src="https://media1.giphy.com/media/s2qXK8wAvkHTO/giphy.gif" alt="SNL cast member throwing confetti"/>
Huzzah!

Thanks for all the detailed analysis on this one team!
