### ISSUE TITLE
Meet with SecEng to discuss using MS Automate as part of the log ingestion process.

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/SecDev-Tools#29]
@baristaTam has had success ingesting dorkbot logs into Splunk using MS Automate. @ddriddle please setup a quick call so we can pick her brain about what worked best and whether there's anything in that pattern we should copy for the GitHub logs ingestion. 

Thanks!

**Comment by ddriddle** [comment]
The meeting is scheduled for next Tuesday, 9/29/2020 at 1:30 PM

**Comment by ddriddle** [comment]
@edthedev's notes from today's meeting with some annotations and editing by myself:

For the GitHub log ingestion, we want an API endpoint that uses the AuthN that [GitHub supports](https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/securing-your-webhooks), and transform it into a POST based AuthN that Splunk can accept to avoid the possibility of leaking the HEC token in logs at GitHub or in our Splunk servers. In a future version, we may add a queue to the back end and have Splunk consume directly from the queue to improve reliability and resilience when Splunk is down.

To avoid the "everything is Python Lambda on AWS" tunnel-vision, we asked a few members of SecEng to look at the problem through the lens of MS Automate. (Also because we do ingest DorkBot via MS Automate now.)

* MS Automate does have the ability to act as a trivial REST API endpoint.
* But there are rate limits on usage that would not scale to the expected logs from several GitHub Orgs.
* And it didn't feel like the REST API endpoint aspect of MS Automate was meant to be used as a core feature - more as a way to get edge cases into an MS Automate flow.
